### ISSUE TITLE
How can I connect remote solrCloud with solrJ?

### ISSUE THREAD

**Issue by zhangddjs** [docker-solr/docker-solr-examples#9]
When I try to connect solrCloud with solrJ using host ip, I found that the livenodes' ip is always the containers' ip, obviously, unreachable.
How can I connect solrCloud from a remote java client?

**Comment by dsmiley** [comment]
I believe you have to set the SOLR_HOST env var to a client accessible hostname, and this should wind up in livenodes in ZK.

**Comment by zhangddjs** [comment]
okay~ I set the Solr_Host and DNS, then it succeed.

``` yml
solr4:
    image: solr:7.5
    container_name: solr4
    ports:
     - "30008:30008"
    environment:
      - ZK_HOST=solr-zk1:2181,solr-zk2:2181,solr-zk3:2181
      - SOLR_PORT=30008
      - SOLR_HOST=dev.covfefe.com
    extra_hosts:
      - dev.covfefe.com:10.100.13.173
    networks:
      - solr-cloud
    depends_on:
      - solr-zk1
      - solr-zk2
      - solr-zk3
```
